### ISSUE TITLE
Ability to install or pull default docker images

### ISSUE THREAD

**Issue by thepenguinthatwants** [skanehira/docui#108]
As some users have load of images that they use as default. It would be nice to be able to pull certain images automatically if they are not already installed on system.

When using docker at first run it feels cumbersome to load one by one and sometimes some might forget what images to use.

**Comment by skanehira** [comment]
@thepenguinthatwants 
Excuse me.
Please tell me what detail of feature you want.

**Comment by thepenguinthatwants** [comment]
A feature that you can define default docker images to config.yaml.

And with one command it pulls them all.

**Comment by inductor** [comment]
docui is just a ui tool to display the components that's running on docker.
There's nothing to do with docker pull and push with it.

When exactly do you want to use the feature you are requesting? 🤔

**Comment by inductor** [comment]
@skanehira Maybe we can close the issue for now.

**Comment by skanehira** [comment]
@thepenguinthatwants 
I think that writing bash will satisfy your use case, so docui does not support it.

@inductor Thank you.
