### ISSUE TITLE
It won't start

### ISSUE THREAD

**Issue by octavz** [skanehira/docui#118]
I am on Ubuntu 18.04.

Followed the installation steps but it just says 

panic: unable to connect to Docker

goroutine 1 [running]:
github.com/skanehira/docui/panel.(*Gui).init(0xc000550000)
	/home/xxx/go/src/github.com/skanehira/docui/panel/gui.go:241 +0x1057
github.com/skanehira/docui/panel.New(0x2, 0xc0000b83c0, 0x9465fe)
	/home/xxx/go/src/github.com/skanehira/docui/panel/gui.go:127 +0x10a
main.main()
	/home/xxx/go/src/github.com/skanehira/docui/main.go:50 +0x358
g]:

**Comment by octavz** [comment]
also ran the docker version and it says the same.

**Comment by skanehira** [comment]
@octavz Hi
It's looks like your docker engine didn't start.
Please check your docker deamon status

```
sudo service docker status
```

**Comment by skanehira** [comment]
time up
