### ISSUE TITLE
error on go get on raspi

### ISSUE THREAD

**Issue by step21** [skanehira/docui#120]
Installation mostly worked. But when compiling the go 11 parts, there is an error. Should this work or is it an unsupported platform?

```GO111MODULE=on go install
# github.com/skanehira/docui/docker
docker/container.go:86: cannot use "github.com/docker/go-connections/nat".PortMap literal (type "github.com/docker/go-connections/nat".PortMap) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortMap in assignment
```

**Comment by skanehira** [comment]
Could you try “go install”?

**Comment by step21** [comment]
Sorry, first error was because I was accidentally still using go 1.8.

But now I get
```
go: verifying github.com/docker/docker@v0.7.3-0.20190111153827-295413c9d0e1: checksum mismatch
        downloaded: h1:vhA3tx0dgFFBPFwU1G3/okGJf9OwRPRpmY9/0IxQOS8=
        go.sum:     h1:5Z3Uksuiv0lpPslfRA25dYUV85hI+Pfvz/Pi1NM2wPA=
#:~/go/src/github.com/skanehira/docui $
```

Which sum does it check? If it checks x86 docker, it will obviously mismatch on arm.

**Comment by skanehira** [comment]
Can you try this?
```
rm -rf go.mod
go mot init
go install
```

**Comment by step21** [comment]
Arch is armv7l

Assuming you mean `go mod init` it says something is wrong.
`﻿﻿/go/src/github.com/skanehira/docui $ go mod init
go: modules disabled inside GOPATH/src by GO111MODULE=auto; see 'go help modules'`

**Comment by dennisfischer** [comment]
Same problem. Ubuntu 19.04 x86_64.

Tried
```
rm -rf go.mod
go mod init
go install
```

```go install``` fails with the same error.

**Comment by skanehira** [comment]
Can you download the binary and try run it?

https://github.com/skanehira/docui/releases

**Comment by skanehira** [comment]
@step21 @dennisfischer 
Did this problem solved?
Please let me know :)

**Comment by skanehira** [comment]
Time up
