### ISSUE TITLE
Doesn't correctly work in Ubuntu18.04

### ISSUE THREAD

**Issue by arwtyxouymz** [skanehira/docui#123]
Hi
I'm really impressed your project and I want to use it.
But it doesn't correctly work in Ubuntu18.04.

## Summary
- Doesn't launch in tmux
- Startup in normal shell, but UI is collapsed
- Using docker, everything work

### Doesn't launch in tmux
If i'm using tmux, docui doesn't launch with no error.
I checked `$HOME/docui.log`, there is no log.
This is preview.
![docui_tmux](https://user-images.githubusercontent.com/16755660/63687743-5f122e80-c840-11e9-8633-b2115e866fcf.gif)

### Startup in normal shell, but UI is collapsed
If i use normal shell (not tmux), `docui` command launch application.
However, UI is something wrong.
Please look at this gif
![docui_normal](https://user-images.githubusercontent.com/16755660/63687763-6d604a80-c840-11e9-969d-7013717dba91.gif)

I'm so sorry the character is too small.
Some vertical black lines are displayed and they hide important characters like 'I' of 'ID' in header.

### Using docker, everything work
If i use dockerized docui, everything work fine.
UI is correct, and if i used tmux, it's fine.
![docui_docker](https://user-images.githubusercontent.com/16755660/63687830-984a9e80-c840-11e9-951e-a8624c847d3a.gif)

## My Environment
- OS: `Ubuntu 18.04.3 LTS`
- docker: Docker version 19.03.1, build `74b1e89`
- docui: `bd2021d6e1b6da00ca7b842679648d577bac0c53`

**Comment by skanehira** [comment]
@arwtyxouymz
Hi, Thank you for using docui :)

>Doesn't launch in tmux

Can you tell me the return code and tmux's version?
I can use docui with tmux in my environment.
The environment is Mac OS and tmux version is 2.9a.

>Startup in normal shell, but UI is collapsed

It's looks like $LC_CTYPE is not "en_US.UTF-8".
Please set "en_US.UTF-8" to LC_CTYPE and try again.

**Comment by arwtyxouymz** [comment]
@skanehira 

Thank you for your help!

> Can you tell me the return code and tmux's version?

`docui` command's exit code is `2` and tmux version is `2.6`

> Please set "en_US.UTF-8" to LC_CTYPE and try again.

After i set `LC_CTYPE` to `en_US.UTF-8`, docui worked fine in normal shell environment!

**Comment by skanehira** [comment]
@arwtyxouymz 
>docui command's exit code is 2 and tmux version is 2.6

What kind of shell are you using?

**Comment by arwtyxouymz** [comment]
@skanehira 

> What kind of shell are you using?

I'm using `zsh`, version is `zsh 5.4.2 (x86_64-ubuntu-linux-gnu)`

**Comment by skanehira** [comment]
@arwtyxouymz 
I fix logger when error occurred, Please update docui and try again.

```
$ git pull
$ go install
```

It's will output to some error message to logger.
Let me know that's error message.

**Comment by arwtyxouymz** [comment]
@skanehira 

I updated docui and ran `docui` again.
Then, i got a error log in `$HOME/docui.log`,

```log
time="2019-08-26T23:45:03+09:00" level=error msg="cannot start docui: terminal entry not found" func=main.run file="/home/user/.golang/src/github.com/skanehira/docui/main.go:27"
```

**Comment by skanehira** [comment]
It’s looks like need $TERM
Please set value as follows and try again.

TERM=xterm-256color

**Comment by arwtyxouymz** [comment]
@skanehira 
Sorry for late.

After i changed $TERM to `xterm-256color`, it worked!
Thanks for your help!
