### ISSUE TITLE
Install Fatal Error

### ISSUE THREAD

**Issue by tonyclemmey** [skanehira/docui#134]
[docui]$ GO111MODULE=on go install
go: github.com/gdamore/tcell@v1.1.1 requires
	github.com/lucasb-eyer/go-colorful@v0.0.0-20181028223441-12d3b2882a08: invalid version: git fetch --unshallow -f origin in /home/opc/go/pkg/mod/cache/vcs/2fc5bab6cd3ef0c920eeabfa5c7746c40404d04ccd5ffc9fd02329dc2b521976: exit status 128:
	fatal: git fetch-pack: expected shallow list

**Comment by skanehira** [comment]
@tonyclemmey Can you tell me your git version?

```
$ git version
```

**Comment by skanehira** [comment]
Closed because there is no reply.
