### ISSUE TITLE
bug: execution with ctrl-e only works once

### ISSUE THREAD

**Issue by timhemel** [skanehira/docui#137]
If I execute a command via ctrl-e on a container, and then try it again (on the same or any other container), the second is never executed. If I restart `docui`, I can execute the command again.

Version information:

```
 docker    | api version:1.40 server version:19.03.11 endpoint:unix:///var/run/docker.sock                                                                                                    
 docui     | version:2.0.4                                                                        
```

**Comment by skanehira** [comment]
fixed in c082399
please update docui
