### ISSUE TITLE
Support go get?

### ISSUE THREAD

**Issue by inductor** [skanehira/docui#24]
Any plan to support `go get github.com/skanehira/docui` ?
Building from the source is not always great as it takes time :)

**Comment by skanehira** [comment]
@inductor 
Thank you for the issue.
As you pointed out, we decided to release the binary because the build takes time.

If you do not mind, please download it from here and use it.

```
https://github.com/skanehira/docui/releases/tag/1.0.0-pre-alpha
```

**Comment by inductor** [comment]
go get command worked with it thanks!
