### ISSUE TITLE
Request: support arrow keys ↑↓

### ISSUE THREAD

**Issue by AkihiroSuda** [skanehira/docui#25]

**Comment by skanehira** [comment]
@AkihiroSuda 
Thanks for the request

I am going to support,
Please tell me which panel arrow keys you want to support.

Support moving between panels?

**Comment by AkihiroSuda** [comment]
I expect ↑↓ to work for selecting an entry in a panel, as in `j` and `k`

**Comment by skanehira** [comment]
@AkihiroSuda 
I supported arrow keys ↑↓ in this [commit](https://github.com/skanehira/docui/commit/d19255b5cefa7ec0bf0b11de9c79d95cf1dd4358).
Please update docui use `go get -u`.

```
go get -u github.com/skanehira/docui
```

**Comment by AkihiroSuda** [comment]
thanks!

**Comment by skanehira** [comment]
@AkihiroSuda 
If you have any requests or improvements,
please give me issue or pull request at any time.

Thank you.
