### ISSUE TITLE
対話型コンテナ -i -t /bin/bash の対応

### ISSUE THREAD

**Issue by friendbear** [skanehira/docui#26]
エンターで対話型コンテナに移りたいのですが、可能でしょうか。

<http://docs.docker.jp/engine/userguide/dockerizing.html#id2>

**Comment by skanehira** [comment]
@friendbear 
結論からいうと、アタッチ機能の対応はするつもりですが、対応できるかどうか、
現在のところ見えていません。

コンテナへのアタッチ対応は以前から検討していますが、
gocuiの仕様上、アタッチ後の標準入出力をリアルタイムで出力するのができないため、
一度gocuiプロセスをサスペンドして、
サブプロセスでアタッチ処理をすることで、実現が可能と見込んでいます。

アタッチ機能自体は、便利なので導入したいと考えていますが、
現在は優先度下げています。

一旦、このissueを課題とさせてください。

**Comment by friendbear** [comment]
@skanehira さん 
![img](https://i0.wp.com/blog.docker.com/wp-content/uploads/2014/03/docker-execdriver-diagram.png)
docker -> libcontainer -> container なので exec -i -t は難しいのかもしれません。知識不足で申し訳ありません。

**Comment by skanehira** [comment]
@friendbear 
`docker run -it`自体は使用しているDockerライブラリがサポートしているので、アタッチすることはできます。（頂いたソースと同様なことはできることを確認しています）

ただ、アタッチしたあとの標準出力をgocuiで出力することができないところが課題ですね。

**Comment by skanehira** [comment]
@friendbear 
gocuiを一度させることで、コンテナへのアタッチとアタッチからの復帰を実現することができました。
すこし調整が必要なので、近いうちにリリースできる見込みなのでもう少しお待ち下さい。

https://asciinema.org/a/221482

**Comment by skanehira** [comment]
This issue was completed.

**Comment by friendbear** [comment]
@skanehira thank's 
Good Job
