### ISSUE TITLE
Cannnot attach container from remote access.

### ISSUE THREAD

**Issue by ryoryotaro** [skanehira/docui#38]
When I press `a` in container list panel,there is no system reaction and can't attach container.
But I run `docker attach` commnad from prompt, it runs normaly.

Environment
Local OS : Windows 10 
Remote OS : Amazon Linux AMI 2018.03
Docker Version : 18.06.1-ce 
Remote access tool  : Teraterm 4.11 and RLogin 2.4

**Comment by skanehira** [comment]
@ryoryotaro 
I added a logger to docui.
Please paste `~/docui.log` on this issue after attach the container.

**Comment by ryoryotaro** [comment]
Thank you for your update.
Docui.log when I attach the container is as follows.

```time="2019-01-23T04:09:53Z" level=info msg="attach container start" func="github.com/skanehira/docui/panel.(*ContainerList).Attach" file="/Users/skanehira/dev/go/src/github.com/skanehira/docui/panel/containerPanel.go:590"
time="2019-01-23T04:09:53Z" level=error msg="exec: \"docker\": executable file not found in $PATH" func="github.com/skanehira/docui/panel.(*ContainerList).Attach" file="/Users/skanehira/dev/go/src/github.com/skanehira/docui/panel/containerPanel.go:606"
time="2019-01-23T04:09:53Z" level=info msg="attach container finished" func="github.com/skanehira/docui/panel.(*ContainerList).Attach" file="/Users/skanehira/dev/go/src/github.com/skanehira/docui/panel/containerPanel.go:609"
time="2019-01-23T04:09:53Z" level=info msg="docui start" func=main.main file="/Users/skanehira/dev/go/src/github.com/skanehira/docui/main.go:14"```

**Comment by skanehira** [comment]
@ryoryotaro 
There have the following error.

```
time="2019-01-23T04:09:53Z" level=error msg="exec: \"docker\": executable file not found in $PATH" func="github.com/skanehira/docui/panel.(*ContainerList).Attach" file="/Users/skanehira/dev/go/src/github.com/skanehira/docui/panel/containerPanel.go:606"
```

It seems that `PATH` does not include `docker`.
I think that you can execute it by including the `docker` in PATH.

**Comment by ryoryotaro** [comment]
Which PATH docui container or host machine ?
In docui container,docker is not installed.
In host machine, docker is installed and `PATH` is `/usr/bin/docker`.

**Comment by skanehira** [comment]
@ryoryotaro 
When attach to container docui call `docker attach` internally.
Therefore, in the environment running docui, you need the docker command.

I plan to improve so that we don't need Docker int the future.

**Comment by ryoryotaro** [comment]
OK, Thanks .
So this is proposal that to implement `shell login function` instead of attach. Because  as far as I know, `docker attach` is not so match used and I use 'docker exec -it <container id> /bin/bash' for login container.

**Comment by ryoryotaro** [comment]
I'm looking forward to your support.
Thank a lot.

**Comment by skanehira** [comment]
@ryoryotaro 
I supported use `docker exec` to attach container in this commit.
#52 

Please update docui and use it.

Let me know if that works for you.
If there is no problem, I'll close this issue.

**Comment by ryoryotaro** [comment]
Thanks a lot.
I updated docui and confirmed `docker exec` worked fine !
But,it's better change the name at the top of the popup and "Attach" button name.
![2019-01-28_10h02_32](https://user-images.githubusercontent.com/16929973/51809645-d18c5180-22e5-11e9-9047-f6782c792569.png)

**Comment by skanehira** [comment]
@ryoryotaro 
Thanks.
I fixed that in this commit.
#55
