### ISSUE TITLE
Docker endpoint should be able to be overwritten by argument/environment variable

### ISSUE THREAD

**Issue by inductor** [skanehira/docui#47]
Currently, the docker endpoint is hard-coded and cannot be changed

https://github.com/skanehira/docui/blob/master/docker/docker.go#L14

However, several users use Docker on a remote host and may be find hard to use this tool on such an environment.

Suggestion:
- Make the const be able to overwritten by an argument like `docui --endpoint https://x.x.x.x:xxxx`
- Using `DOCKER_HOST` is preferable when the argument is not specified.
- UNIX socket, HTTPS(TLS), SSH should be supported as Docker supports those.

**Comment by skanehira** [comment]
@inductor 
It takes time but I plan to deal with it.

**Comment by inductor** [comment]
https://github.com/skanehira/docui/pull/70 !!!
