### ISSUE TITLE
can't run docui on macOS

### ISSUE THREAD

**Issue by mimikun** [skanehira/docui#66]
Thank you for creating useful tools.
A problem occurred when installing.

I did:

```
$ go get -d github.com/skanehira/docui
$ cd $GOPATH/src/github.com/skanehira/docui
$ GO111MODULE=on go install
$ docui
panic: invalid dimensions

goroutine 1 [running]:
github.com/skanehira/docui/panel.(*Gui).init(0xc000072300)
	/Users/mimikun/go/src/github.com/skanehira/docui/panel/gui.go:192 +0xf57
github.com/skanehira/docui/panel.New(0x2, 0x1446a20)
	/Users/mimikun/go/src/github.com/skanehira/docui/panel/gui.go:94 +0x138
main.main()
	/Users/mimikun/go/src/github.com/skanehira/docui/main.go:13 +0x2e
```

my envrionments:
- macOS 10.14.2
- Docker CE v18.09.1
- Go v1.11.4 darwin/amd64

Thanks.

**Comment by skanehira** [comment]
@mimikun 
Thank you issue.
If screen size is too small, it will not work.
Please increase the size of terminal and tell me whether it works or not.

I'll resolve this bug in the near future.

**Comment by skanehira** [comment]
@mimikun 
>I think, an error occurs if the number of rows is less. 
That right.
If screen is too small, docui cannot draw screen.
That is gocui's specification.

**Comment by mimikun** [comment]
I see.
Thank you!
