### ISSUE TITLE
Brew support

### ISSUE THREAD

**Issue by FernandoMiguel** [skanehira/docui#91]
like https://github.com/skanehira/docui/issues/83
but support for home brew

**Comment by gotchane** [comment]
I thought the same thing! May I work on this issue?

**Comment by FernandoMiguel** [comment]
> I thought the same thing! May I work on this issue?

pls do!

**Comment by skanehira** [comment]
@FernandoMiguel @gotchane 
Thank you!

**Comment by gotchane** [comment]
@skanehira

I researched the way to support HomeBrew.

To support official homebrew repo, it seems that it takes some lead time.

To support quickly, it seems better to use `brew tap` as third-party repo.

https://docs.brew.sh/Taps

But the repo name of tap is like `username/repo`.
When I create a tap, brew install commands are as below.

```
brew tap gotchane/docui
brew install docui
```

Do you think which is more important, to support quickly or to support officially?

**Comment by skanehira** [comment]
@gotchane 
Thank you Propose.
brew tap is a binary downloaded from the github release,
is it also the same in the official repository?

If possible, I would like to build from master instead of release so that I can download the latest version

This article may be helpful.
https://qiita.com/knqyf263/items/53dd0d0916afc5472281

**Comment by gotchane** [comment]
@skanehira 

Thanks for your reply.

> brew tap is a binary downloaded from the github release,
> is it also the same in the official repository?

That's right...!
OK, I'll try to send PR to official HomeBrew repo.

> I would like to build from master instead of release so that I can download the latest version

It looks so nice! I'll check this article.
Thanks!
